spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  application:
    name: springboot-jpa
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: update